version: '3.9'

services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
      - ./logs:/var/log/nginx
      - ./certs:/etc/nginx/certs
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    driver: bridge
